# Monitor config which relies on automatic monitor resloution
source = $HOME/.config/hypr/monitor_definitions.conf

monitor=,preferred,auto,auto  # For any new, unlisted monitors


$scale = 1.5
# Home monitors
$monitor_width = {{3840 / $scale}}
$monitor_height = {{2160 / $scale}}
$offset = {{720 / $scale}}
monitor= $vertical, prefered, 0x0, $scale, transform, 1
monitor= $horizontal, prefered, $monitor_height x $offset, $scale
monitor= eDP-1, preferred, $monitor_width x {{$monitor_height + $offset}}, $scale

# monitor=eDP-1,3840x2400@120.0,1440x1920,1.5
# monitor=DP-7,3840x2160@29.98,1440x480,1.5
# monitor=DP-9,3840x2160@29.98,0x0,1.5
# monitor=DP-9,transform,1
